### ISSUE TITLE
About pipenv's installation command suggestion

### ISSUE THREAD

**Issue by DriftKingTW** [johnliu55tw/InnovationChat-20#1]
Hi, 
about the pipenv installation tutorial in README.md file:
`$ pip install pipenv`
I think it should be
`$ pip3 install pipenv`
Otherwise, if you have python 2 and 3 install in system at the same time it will cause some errors.

Regards, 
DriftKingTW

**Comment by johnliu55tw** [comment]
Great suggestion, but I think the user that wants to install `pipenv` should deal with this problem by him/herself.

`pipenv` supports both Python2 and Python3, which means it can be installed by either pip2 or pip3. Furthermore, its official installation guide does not restrict its users to only use Python2 or Python3 (Although the use of Python3 is highly recommended, see [here](https://docs.pipenv.org/#install-pipenv-today)), so I don't think `pip3` should be explicitly specified in the installing command.
